# GitHub Pages Configuration for Black Lion Cafe
title: Black Lion Cafe - Business Profile
description: Complete business profile and contact information for Black Lion Cafe in Rockville, Maryland
url: ""
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# SEO settings
lang: en_US
author: Business Profile Generator

# Social media
social:
  name: Black Lion Cafe
  links: []
