# GitHub Pages Configuration for Teamania
title: Teamania - Business Profile
description: Complete business profile and contact information for Teamania in Rockville, Maryland
url: ""
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# SEO settings
lang: en_US
author: Business Profile Generator

# Social media
social:
  name: Teamania
  links: []
